In [34]:
import pandas as pd

df = pd.read_excel('data/新闻.xlsx')

titles = df['标题']

titles

0                      信托公司2019年上半年经营业绩概览
1                            首单信托型企业ABS获批
2                 华能贵诚信托孙磊:金融科技助力打造开放信托生态
3            华能贵诚信托孙磊:金融科技已经成为信托行业重要的基础设施
4                格力电器股权转让意向方闭门开会 华能信托赫然在列
                      ...                
957    2019京东手机金机奖大众投票开启:5G前夜,用户青睐什么样的手机?
958      2019京东手机金机奖评选火热进行中,快来看看你的机型入选了吗?
959               德国大闸蟹泛滥成灾 其实他们可以找京东生鲜合作
960      德国吸尘器大牌Fakir费卡伊尔登陆京东 除尘电器领域新势力来袭
961          京东、百度加入收费阵营 信用卡还款是否还有“免费午餐”?
Name: 标题, Length: 962, dtype: object

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(titles)


In [37]:
row = X.toarray()[:3]

for r in row:
    print(vectorizer.get_feature_names_out()[r.ravel().nonzero()[0]])

['信托公司2019年上半年经营业绩概览']
['首单信托型企业abs获批']
['华能贵诚信托孙磊' '金融科技助力打造开放信托生态']


In [38]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [39]:
print(vectorizer.get_feature_names_out())

['00700' '03亿' '08s特别版京东众筹中' ... '黑客都用python' '黑科技' '鼻祖']


In [40]:
X = vectorizer.fit_transform(titles)

X

<962x2015 sparse matrix of type '<class 'numpy.int64'>'
	with 2427 stored elements in Compressed Sparse Row format>

In [41]:
print(vectorizer.get_feature_names_out())

['00700' '03亿' '08s特别版京东众筹中' ... '黑客都用python' '黑科技' '鼻祖']


In [42]:
X = vectorizer.fit_transform(titles)

X

<962x2015 sparse matrix of type '<class 'numpy.int64'>'
	with 2427 stored elements in Compressed Sparse Row format>

In [43]:
print(vectorizer.get_feature_names_out())

['00700' '03亿' '08s特别版京东众筹中' ... '黑客都用python' '黑科技' '鼻祖']


In [44]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [45]:
df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

df

00700  03亿  08s特别版京东众筹中  0业务模式升级拉开序幕  0建设  10  100  100万个工作岗位  \
0        0    0            0            0    0   0    0          0   
1        0    0            0            0    0   0    0          0   
2        0    0            0            0    0   0    0          0   
3        0    0            0            0    0   0    0          0   
4        0    0            0            0    0   0    0          0   
..     ...  ...          ...          ...  ...  ..  ...        ...   
957      0    0            0            0    0   0    0          0   
958      0    0            0            0    0   0    0          0   
959      0    0            0            0    0   0    0          0   
960      0    0            0            0    0   0    0          0   
961      0    0            0            0    0   0    0          0   

     10个python简单技巧  12  ...  高质量办好民族体育盛会  高通纷纷屈服  高通骁龙开启数字娱乐新篇章  鲜花分分钟送达  \
0                0   0  ...            0       0              0        0   
1                0   0  ...            0       0              0        0   
2                0   0  ...            0       0              0        0   
3                0   0  ...            0       0              0        0   
4                0   0  ...            0       0              0        0   
..             ...  ..  ...          ...     ...            ...      ...   
957              0   0  ...            0       0              0        0   
958              0   0  ...            0       0              0        0   
959              0   0  ...            0       0              0        0   
960              0   0  ...            0       0              0        0   
961              0   0  ...            0       0              0        0   

     麦积山石窟  麦锐娱乐否认倒闭传闻  黄釉瓷器众筹爆红京东  黑客都用python  黑科技  鼻祖  
0        0           0           0           0    0   0  
1        0           0           0           0    0   0  
2        0           0           0           0    0   0  
3        0           0           0           0    0   0  
4        0           0           0           0    0   0  
..     ...         ...         ...         ...  ...  ..  
957      0           0           0           0    0   0  
958      0           0           0           0    0   0  
959      0           0           0           0    0   0  
960      0           0           0           0    0   0  
961      0           0           0           0    0   0  

[962 rows x 2015 columns]

In [46]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0, max_iter=300).fit(X)

kmeans.labels_

D:\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [49]:
kmeans = KMeans(n_clusters=3, random_state=0, max_iter=300, init='k-means++').fit(X)

kmeans.labels_

D:\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,